name: Sync Localisation

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Sync Localisation
        run: |
          # Check if the commit affected localisation folder
          if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- "localisation/") ]]; then
            # Clone the Localisation_IRIS repository
            git clone --depth 1 https://github.com/Rekordny/Localisation_IRIS.git
            
            # Copy the localisation folder to Localisation_IRIS repository
            cp -r "localisation/" Localisation_IRIS/
            
            # Push changes to Localisation_IRIS repository
            cd Localisation_IRIS
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Sync localisation folder from Project_IRIS"
            git push origin main
          else
            echo "No changes in the localisation folder."
          fi
