name: Sync Localisation to Localisation_IRIS

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Filter YAML files
        id: filter
        run: |
          # Find all .yml files in localisation folder and store in a variable
          yml_files=$(find localisation/ -type f -name '*.yml')
          echo "::set-output name=yml_files::$yml_files"
          
      - name: Clone Localisation_IRIS repository
        run: git clone --depth 1 https://github.com/Rekordny/Localisation_IRIS.git Localisation_IRIS
        
      - name: Copy YAML files
        run: |
          # Copy filtered .yml files to Localisation_IRIS repository
          IFS=$'\n'
          for file in ${YML_FILES[@]}; do
            cp "$file" Localisation_IRIS/
          done
          
      - name: Push changes to Localisation_IRIS
        run: |
          cd Localisation_IRIS
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Sync localisation .yml files from Project_IRIS"
          git push origin main
